CREATE TABLE rescue_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL
);

CREATE TABLE rescue_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_code VARCHAR(50) NOT NULL UNIQUE,
    rescue_date DATE NOT NULL,
    rescue_location VARCHAR(150) NOT NULL,
    status VARCHAR (30) NOT NULL,
    rescue_center_id BIGINT NOT NULL,

    CONSTRAINT fk_rescue_cases_center FOREIGN KEY (rescue_center_id) REFERENCES rescue_centers(id),

    CONSTRAINT chk_rescue_cases_status
        CHECK(
            status IN (
                'ADMITTED',
                'UNDER_EVALUATION',
                'IN_REHABILITATION',
                'READY_FOR_RELEASE',
                'RELEASED',
                'CLOSED'
            )
        )
);

CREATE TABLE animals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_code VARCHAR(50) UNIQUE,
    common_name VARCHAR(100),
    scientific_name VARCHAR(150),
    sex VARCHAR(20),
    rescue_case_id BIGINT UNIQUE,

    CONSTRAINT fk_animals_rescue_case FOREIGN KEY (rescue_case_id) REFERENCES rescue_cases(id)

/*.
.
.
.
.
.
.
    HACE FALTA PONER EL CHECK DE SEX
.
.
.
.
.
.
.
.
.*/

);

CREATE TABLE medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id BIGINT NOT NULL UNIQUE,
    initial_weight DECIMAL(6,2) NOT NULL,
    initial_condition VARCHAR(100) NOT NULL,
    injuries VARCHAR(500),
    observations VARCHAR(500),

    CONSTRAINT fk_medical_records_animal
        FOREIGN KEY (animal_id)
        REFERENCES animals(id)
);

CREATE TABLE specialists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_code VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150)  NOT NULL UNIQUE,
    active BOOLEAN NOT NULL
);

CREATE TABLE expertise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE specialist_expertise (
    specialist_id BIGINT NOT NULL,
    expertise_id BIGINT NOT NULL,

    CONSTRAINT fk_specialist_expertise_specialist
        FOREIGN KEY (specialist_id)
        REFERENCES specialists(id),

    CONSTRAINT fk_specialist_expertise_expertise
        FOREIGN KEY (expertise_id)
        REFERENCES expertise(id),

    PRIMARY KEY (specialist_id, expertise_id)
);

CREATE TABLE treatments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    performed_at TIMESTAMP NOT NULL,
    type VARCHAR(50) NOT NULL,
    description VARCHAR(500),

    CONSTRAINT fk_treatments_animal
        FOREIGN KEY (animal_id)
        REFERENCES animals(id),

    CONSTRAINT fk_treatments_specialist
        FOREIGN KEY (specialist_id)
        REFERENCES specialists(id)

/*.
.
.
.
.
.
.
    HACE FALTA PONER EL CHECK DE TYPE
.
.
.
.
.
.
.
.
.*/
);

CREATE INDEX idx_rescue_cases_rescue_center_id
    ON rescue_cases(rescue_center_id);

CREATE INDEX idx_rescue_cases_status
    ON rescue_cases(status);

CREATE INDEX idx_rescue_cases_rescue_date
    ON rescue_cases(rescue_date);

CREATE INDEX idx_treatments_animal_id
    ON treatments(animal_id);

CREATE INDEX idx_treatments_specialist_id
    ON treatments(specialist_id);

CREATE INDEX idx_treatments_performed_at
    ON treatments(performed_at);
